// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLydZh-AD_CRB6bje3n2D27I6iA24mwE',
    appId: '1:367336022614:web:f8c11d2e5d966b20e351f7',
    messagingSenderId: '367336022614',
    projectId: 'ceylonmarketplace-38df8',
    authDomain: 'ceylonmarketplace-38df8.firebaseapp.com',
    storageBucket: 'ceylonmarketplace-38df8.firebasestorage.app',
    measurementId: 'G-WGF4FD9TPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Mc_RfqKzFGILmMKpwcGvQzUBAxGrJO8',
    appId: '1:367336022614:android:168fb83a87640c4ee351f7',
    messagingSenderId: '367336022614',
    projectId: 'ceylonmarketplace-38df8',
    storageBucket: 'ceylonmarketplace-38df8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNh8FtchSUNvpwpcM0D2Llsjk0besCG68',
    appId: '1:367336022614:ios:bf478aeb975c5250e351f7',
    messagingSenderId: '367336022614',
    projectId: 'ceylonmarketplace-38df8',
    storageBucket: 'ceylonmarketplace-38df8.firebasestorage.app',
    iosBundleId: 'com.example.ceylonmarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNh8FtchSUNvpwpcM0D2Llsjk0besCG68',
    appId: '1:367336022614:ios:bf478aeb975c5250e351f7',
    messagingSenderId: '367336022614',
    projectId: 'ceylonmarketplace-38df8',
    storageBucket: 'ceylonmarketplace-38df8.firebasestorage.app',
    iosBundleId: 'com.example.ceylonmarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwLydZh-AD_CRB6bje3n2D27I6iA24mwE',
    appId: '1:367336022614:web:9414522a9203623fe351f7',
    messagingSenderId: '367336022614',
    projectId: 'ceylonmarketplace-38df8',
    authDomain: 'ceylonmarketplace-38df8.firebaseapp.com',
    storageBucket: 'ceylonmarketplace-38df8.firebasestorage.app',
    measurementId: 'G-X0XK203PH2',
  );
}
